// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ybgtTylr-p_qCz_MRViC8mDfsew8mNk',
    appId: '1:425915050821:web:e1c8cf7c002f49b8532c2c',
    messagingSenderId: '425915050821',
    projectId: 'untitledtravel-51c09',
    authDomain: 'untitledtravel-51c09.firebaseapp.com',
    storageBucket: 'untitledtravel-51c09.appspot.com',
    measurementId: 'G-K93RFBHD30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtsT7zfOY83dqfYKb-qIUJjFr6hLp0oFU',
    appId: '1:425915050821:android:b6e18338d474a37e532c2c',
    messagingSenderId: '425915050821',
    projectId: 'untitledtravel-51c09',
    storageBucket: 'untitledtravel-51c09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5An4p9DlUKz2zywyphBy5WsmAf3rV1yM',
    appId: '1:425915050821:ios:209d2df4add40387532c2c',
    messagingSenderId: '425915050821',
    projectId: 'untitledtravel-51c09',
    storageBucket: 'untitledtravel-51c09.appspot.com',
    androidClientId: '425915050821-8de6icnspo1v3aktl1rsj0llf6umo0ne.apps.googleusercontent.com',
    iosClientId: '425915050821-5ucknk9pkuniqftsl3gbausiv3b23bsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitledtravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5An4p9DlUKz2zywyphBy5WsmAf3rV1yM',
    appId: '1:425915050821:ios:209d2df4add40387532c2c',
    messagingSenderId: '425915050821',
    projectId: 'untitledtravel-51c09',
    storageBucket: 'untitledtravel-51c09.appspot.com',
    androidClientId: '425915050821-8de6icnspo1v3aktl1rsj0llf6umo0ne.apps.googleusercontent.com',
    iosClientId: '425915050821-5ucknk9pkuniqftsl3gbausiv3b23bsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitledtravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ybgtTylr-p_qCz_MRViC8mDfsew8mNk',
    appId: '1:425915050821:web:8dc436d1d2943c2c532c2c',
    messagingSenderId: '425915050821',
    projectId: 'untitledtravel-51c09',
    authDomain: 'untitledtravel-51c09.firebaseapp.com',
    storageBucket: 'untitledtravel-51c09.appspot.com',
    measurementId: 'G-12QHT002BK',
  );
}
